spring:
  application:
    name: PixelArt
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    locations: classpath:db/migration

surofu:
  pixelart:
    app:
      jwt:
        secret: ${JWT_SECRET}
        lifetime: 1d
        refresh-lifetime: 30d